#!/bin/zsh -e

readonly GIT_URL="git://slackbuilds.org/slackbuilds"
readonly SLACKBUILD_SHELL=/bin/bash
readonly FAKEROOT=/usr/bin/fakeroot
readonly SUDO=/usr/bin/sudo
readonly PKGDB=/var/log/packages
readonly PAGER=${PAGER:-more}

#-----------------------------------------------------------------------------#

debug() {
    # print "DEBUG: $@" 1>&2
}

warn() {
    print "Warning: $@" 1>&2
}

die() {
    print "Error: $@" 1>&2
    exit 1
}

#-----------------------------------------------------------------------------#

find_pkg_dir() {
    local pkg pkg_dir softly
    pkg=$1
    softly=${2:-no}
    pkg_dir=( $REPO/*/$pkg(N) )
    if [[ $#pkg_dir == 0 && $softly != softly ]]
    then
        die "$pkg not found"
    fi
    print -- $pkg_dir[1]
}

#-----------------------------------------------------------------------------#

split_pkg_name() {
    # For speed, the results are left in the array `match'.
    if [[ ${1:t} =~ \(.*\)-\([^-]*\)-\([^-]*\)-\(.*\) ]]
    then
        return
    else
        match=( $longname UNKNOWN_VERSION )
    fi
}

same_version_installed() {
    local -r pkg=$1
    local -r pkg_dir=$(find_pkg_dir $pkg)
    local -r info=$pkg_dir/$pkg.info
    . $info # XXX makes a mess

    local found
    found=( $PKGDB/$PRGNAM-$VERSION-*-*(N) )
    if [[ $#found > 0 ]]
    then
        return 0
    fi
    return 1
}

some_version_installed() {
    local -r pkg=$1
    local file
    for file in $PKGDB/${pkg}*(N)
    do
        split_pkg_name $file
        if [[ $match[1] == $pkg ]]
        then
            return 0
        fi
    done
    return 1
}

#-----------------------------------------------------------------------------#

excluded=()
seen=()
queue=()

is_excluded() {
    if (( ${+excluded[(re)$1]} ))
    then
        return 0
    fi
    return 1
}

is_seen() {
    if (( ${+seen[(re)$1]} ))
    then
        return 0
    fi
    return 1
}

in_queue() {
    if (( ${+queue[(re)$1]} ))
    then
        return 0
    fi
    return 1
}

add_deps() {
    local pkg=$1
    if is_excluded $pkg
    then
        debug "$pkg excluded"
        return
    fi

    local pkg_dir=$(find_pkg_dir $pkg)
    [[ -d $pkg_dir ]] || exit 1
    local info=$pkg_dir/$pkg.info
    . $info # XXX makes a mess

    seen+=$pkg
    debug "seen $pkg"
    local req
    for req in ${=REQUIRES}
    do
        if [[ $req == "%README%" ]]
        then
            continue
        fi
        if in_queue $req
        then
            debug "$req already queued"
            continue
        fi
        if is_seen $req
        then
            die "circular dependency detected: $req"
        fi
        add_deps $req
    done
    debug "$pkg queued"
    queue+=$pkg
}

#-----------------------------------------------------------------------------#

verify_file() {
    local md5=$1
    local fn=$2
    if [[ ! -f $fn ]]
    then
        debug "file does not exist: $fn"
        return 1
    fi
    # This extension is useful for certain custom slackbuilds.
    if [[ $md5 == UNKNOWN ]]
    then
        warn "MD5 sum is UNKNOWN; skipping check."
        return 0
    fi
    local digest=$( md5sum $fn | cut -d' ' -f1 )
    if [[ $digest == $md5 ]]
    then
        debug "file exists and verified: $fn"
        return 0
    else
        warn "MD5 sum does not match: $fn"
    fi
    return 1
}

percent_decode() {
    echo -e ${1//'%'/'\x'}
}

content_disposition_filename() {
    # XXX hack only works in simple cases.
    if [[ $1 =~ $'[Cc]ontent-[Dd]isposition:.*; filename="?([^"\x0d\x0a]*)' ]]
    then
        percent_decode ${match[1]:t}
    else
        return 1
    fi
}

sbosrcarch() {
    local src=$1
    local md5=$2
    print "http://slackware.uk/sbosrcarch/by-md5/${md5:0:1}/${md5:1:1}/${md5}/${src:t}"
}

# Returns: srcfn
check_and_download() {
    local src=$1
    local md5=$2

    srcfn=$(percent_decode ${src:t})
    if (( ! $mode_forcedownload )) && verify_file $md5 $srcfn
    then
        return 0
    fi

    # Might want to restrict this to known providers, e.g. github.
    local curlout="$( ${=CURL} -s -I $src )"
    local remotefn="$( content_disposition_filename $curlout )"
    if [[ $remotefn != '' ]]
    then
        debug "remote filename: $remotefn"
        srcfn=$remotefn
        if (( ! $mode_forcedownload )) && verify_file $md5 $srcfn
        then
            return 0
        fi
    fi

    # curl -O does not percent-decode.
    print "Downloading $src" >&2
    if ! ${=CURL} $src -o $srcfn
    then
        local altsrc=$(sbosrcarch $src $md5)
        print "Downloading $altsrc" >&2
        if ! ${=CURL} $altsrc -o $srcfn
        then
            die "failed to download $altsrc"
        fi
    fi
    if ! verify_file $md5 $srcfn
    then
        die "MD5 sum does not match: $srcfn"
    fi
    return 0
}

# Returns: srcfns
download_src() {
    local pkg=$1
    local pkg_dir=$(find_pkg_dir $pkg)
    local info=$pkg_dir/$pkg.info
    . $info # XXX makes a mess

    local dlarch="${ARCH:-$(uname -m)}"
    case $dlarch in
        arm*) dlarch=arm ;;
    esac

    local md5s srcs
    if [[ $dlarch == x86_64 && $DOWNLOAD_x86_64 == UN* ]]
    then
        warn "$pkg is $DOWNLOAD_x86_64 on x86_64."
        srcs=( ${=DOWNLOAD} )
        md5s=( ${=MD5SUM} )
    elif [[ $dlarch == x86_64 && -n $DOWNLOAD_x86_64 ]]
    then
        srcs=( ${=DOWNLOAD_x86_64} )
        md5s=( ${=MD5SUM_x86_64} )
    elif [[ $dlarch == arm && -n $DOWNLOAD_arm ]] # non-standard extension
    then
        srcs=( ${=DOWNLOAD_arm} )
        md5s=( ${=MD5SUM_arm} )
    else
        srcs=( ${=DOWNLOAD} )
        md5s=( ${=MD5SUM} )
    fi

    local srcfn
    while (( $#md5s > 0 ))
    do
        local src=$srcs[1]
        local md5=$md5s[1]
        shift srcs
        shift md5s
        if ! check_and_download $src $md5
        then
            die "failed to download $src"
        fi
        srcfns[$srcfn]=${src:t} # return value
    done

    if (( $#dls > 0 ))
    then
        die "list length mismatch"
    fi
}

#-----------------------------------------------------------------------------#

maybe_fakeroot() {
    if [[ $UID != 0 && -x $FAKEROOT ]]
    then
        debug "running $FAKEROOT $@ in $PWD"
        command $FAKEROOT "$@"
        return $?
    else
        debug "running $@"
        command "$@"
        return $?
    fi
}

# Implicit parameter: srcfns
build() {
    local -r pkg=$1
    local -r pkg_dir=$(find_pkg_dir $pkg)
    local -r stagedir=$STAGEDIR/$pkg
    local -r builddir=$stagedir/build
    shift 1

    rm -rf $stagedir
    mkdir -p $stagedir $builddir
    cp -r $pkg_dir/* $stagedir

    local fn otherfn
    for fn in ${(k)srcfns}
    do
        otherfn=${srcfns[$fn]}
        ln -s $CACHEDIR/$fn $stagedir
        if [[ $fn != $otherfn ]]
        then
            ln -s $CACHEDIR/$fn $stagedir/$otherfn
        fi
    done

    local olddir=$PWD

    cd $stagedir
    if ! TMP=$builddir maybe_fakeroot $SLACKBUILD_SHELL $pkg.SlackBuild
    then
        die "error building $pkg"
    fi

    cd $olddir
}

#-----------------------------------------------------------------------------#

remove_stagedir() {
    local -r pkg=$1
    local -r pkg_dir=$(find_pkg_dir $pkg)
    local -r stagedir=$STAGEDIR/$pkg

    if [[ -d $stagedir ]]
    then
        if ! rm -rf $stagedir
        then
            die "error removing $stagedir"
        fi
        echo "Removed $stagedir"
    fi
}

#-----------------------------------------------------------------------------#

extract_built_pkg_filename() {
    local -r logfile=$1
    tail -3 $logfile | grep '^Slackware package .* created[.]$' | cut -d' ' -f3
}

maybe_sudo() {
    if [[ $UID != 0 && -x $SUDO ]]
    then
        debug "running $SUDO $@"
        command $SUDO "$@"
        return $?
    else
        debug "running $@"
        command "$@"
        return $?
    fi
}

install() {
    maybe_sudo /sbin/upgradepkg --install-new --reinstall $1
}

#-----------------------------------------------------------------------------#

# Parse options

mode_help=0
mode_printconfig=0
mode_checkupdates=0
mode_dryrun=0
mode_download=0
mode_forcedownload=0
mode_build=0
mode_install=0
mode_cleanup=0
mode_rebase=0
mode_changelog=0
mode_show=0
mode_showhome=0
mode_searchname=0
mode_searchdesc=0
mode_revdeps=0
mode_recrevdeps=0

while getopts hCcndDbirlsSgGqQx OPT
do
    case $OPT in
        (h)
            mode_help=1
            ;;
        (C)
            mode_printconfig=1
            ;;
        (c)
            mode_checkupdates=1
            ;;
        (n)
            mode_dryrun=1
            ;;
        (d)
            mode_download=1
            ;;
        (D)
            mode_download=1
            mode_forcedownload=1
            ;;
        (b)
            mode_download=1
            mode_build=1
            ;;
        (i)
            mode_download=1
            mode_build=1
            mode_install=1
            ;;
        (x)
            mode_cleanup=1
            ;;
        (r)
            mode_rebase=1
            ;;
        (l)
            mode_changelog=1
            ;;
        (s)
            mode_show=1
            ;;
        (S)
            mode_showhome=1
            ;;
        (g)
            mode_searchname=1
            ;;
        (G)
            mode_searchdesc=1
            ;;
        (q) # reQuires?
            mode_revdeps=1
            ;;
        (Q)
            mode_revdeps=1
            mode_recrevdeps=1
            ;;
        (?)
            die "unrecognised option"
            ;;
    esac
done
shift $(( $OPTIND - 1 ))

case $mode_checkupdates,$mode_download,$mode_build,$mode_install,$mode_cleanup,$mode_rebase,$mode_changelog,$mode_show,$mode_showhome,$mode_searchname,$mode_searchdesc,$mode_revdeps in
    (0,0,0,0,0,0,0,0,0,0,0,0)
        # Default to -i.
        mode_download=1
        mode_build=1
        mode_install=1
        ;;
esac

case $mode_download,$mode_cleanup in
    (1,1)
        die "-x is incompatible with -d, -b and -i"
        ;;
esac

if (( $mode_show + $mode_showhome + $mode_searchname + $mode_searchdesc + $mode_revdeps > 1 ))
then
    die "only one of -s, -S, -g, -G, -q can be specified"
fi

#-----------------------------------------------------------------------------#

# Help

if (( $mode_help ))
then
    cat << EOF
Usage: asbo [OPTION]... [PACKAGE]... [~EXCLUDE-PACKAGE]...
An anti-social SlackBuilds build order organiser.

  -h    display this help
  -C    print configuration

  -d    download sources for named packages and dependencies
  -D    force downloads (implies -d)
  -b    build named packages and dependencies (implies -d)
  -i    install named packages and dependencies (default; implies -b)
  -n    show packages that would be built
  -x    remove build directories for named packages

  -s    show information about named packages
  -S    open home page for named packages
  -g    search by package name
  -G    search by package descriptions
  -q    search for packages directly requiring named packages
  -Q    search for packages requiring named packages (implies -q)

  -r    run git rebase --pull in slackbuilds directory
  -l    show slackbuilds changelog
  -c    show potential updates to installed SBo packages

EOF
    exit
fi

#-----------------------------------------------------------------------------#

# Configuration

cfg=$HOME/.config/asbo/asbo.conf
if [[ ! -f $cfg ]]
then
    cfg=/etc/asbo/asbo.conf
fi
if [[ -f $cfg  ]]
then
    . =( grep -E -e '^(REPO|CACHEDIR|STAGEDIR|LOGDIR|OUTPUT|MAKEFLAGS|CURL)=' $cfg )
fi

prefix=/var/tmp/asbo
readonly REPO=${REPO:-${prefix}/slackbuilds}
readonly CACHEDIR=${CACHEDIR:-${prefix}/cache}
readonly STAGEDIR=${STAGEDIR:-${prefix}/stage}
readonly LOGDIR=${LOGDIR:-${prefix}/log}
readonly CURL=${CURL:-/usr/bin/curl -S -L --max-redirs 10}

export OUTPUT=${OUTPUT:-}
export MAKEFLAGS=${MAKEFLAGS:-}

#-----------------------------------------------------------------------------#

# Print configuration

if (( $mode_printconfig ))
then
    print "REPO=$REPO"
    print "CACHEDIR=$CACHEDIR"
    print "STAGEDIR=$STAGEDIR"
    print "LOGDIR=$LOGDIR"
    print "OUTPUT=$OUTPUT"
    print "CURL=$CURL"
    print "MAKEFLAGS=$MAKEFLAGS"
    exit
fi

#-----------------------------------------------------------------------------#

# Set up repo

if [[ ! -e $REPO ]]
then
    print "Repository directory does not exist:  $REPO"
    print -n "Would you like to clone it with git now [y,n]? "
    read yn
    case $yn in
        ([yY])
            mkdir -p $REPO
            print "Cloning:  git clone $GIT_URL $REPO"
            git clone $GIT_URL $REPO
            ;;
        (*)
            die "Please set up the repository manually."
            exit 1
            ;;
    esac
fi

if [[ ! -d $REPO ]]
then
    die "$REPO is not a directory"
fi

#-----------------------------------------------------------------------------#

if (( $mode_rebase ))
then
    print "Updating repository:  git pull --rebase"
    cd $REPO
    if ! git pull --rebase
    then
        echo "Fix manually $REPO"
        exit 1
    fi
    exit 0
fi

#-----------------------------------------------------------------------------#

highlight_changelog() {
    grep --color=always '^.*: Added .*\|^+--------------------------+\|$' "$@"
}

if (( $mode_changelog ))
then
    cd $REPO
    highlight_changelog ChangeLog.txt | ${=PAGER}
    exit
fi

#-----------------------------------------------------------------------------#

highlight_shell() {
    if command -v highlight >/dev/null
    then
        command highlight --syntax sh --style zmrok -O xterm256 "$@"
    elif command -v pygmentize >/dev/null
    then
        command pygmentize -l sh -O bg=dark,style=lovelace -f terminal256 "$@"
    else
        cat "$@"
    fi
}

show_files() {
    local dir=$1
    (
        cd $dir
        echo "Package: ${dir:t}"
        echo
        if [[ -r README ]]
        then
            cat README
            echo
        fi
        echo "--------"
        echo
        highlight_shell *.info
        echo
        echo "--------"
        echo
        highlight_shell *.SlackBuild
    ) | ${=PAGER}
}

show_homepage() {
    local dir=$1
    (
        cd $dir
        . ./${dir:t}.info
        xdg-open $HOMEPAGE
    )
}

show() {
    local glob dir
    # Interpret shell metacharacters in $1.
    glob=( $REPO/*/${~1}(/N) )
    if (( $#glob == 0 ))
    then
        print "No package found: $1"
        return 1
    fi
    for dir in $glob
    do
        if (( $mode_showhome ))
        then
            show_homepage $dir
        else
            show_files $dir
        fi
    done
}

if (( $mode_show || $mode_showhome ))
then
    for arg
    do
        show $arg
    done
    exit 0
fi

#-----------------------------------------------------------------------------#

search_name() {(
    setopt no_case_glob
    cd $REPO
    glob=( */*${1}*(/N) )
    if (( $#glob == 0 ))
    then
        print "No package found: $1"
        return
    fi
    print -l -- $glob
)}

if (( $mode_searchname ))
then
    for arg
    do
        search_name $arg
    done
    exit 0
fi

#-----------------------------------------------------------------------------#

basic_re_quote() {
    # Basic meta characters:  \ . [ ^ $ \ *
    # Not meta characters:    ? + { | ( )
    sed 's/[\.[^$*]/\\&/g' <<< "$*"
}

if (( $mode_searchdesc ))
then
    cd $REPO
    term=$(basic_re_quote $1)
    files=($(grep -l -i -e "^[^:]*: .*${term}" */*/slack-desc))
    remaining=$#files
    for file in $files
    do
        sed -n -e '/^[^: ]*:/  s/^[^:]*: \?//  p' $file
        if (( $remaining > 1 ))
        then
            echo
            echo "--------"
            echo
            (( remaining-- ))
        fi
    done | cat -s | grep --color=always -i -e "$term\|$" | ${=PAGER}
    exit 0
fi

#-----------------------------------------------------------------------------#

revdeps() {
    local -r pkg=$(basic_re_quote $1)
    cd $REPO
    # grep -l -G -e "^REQUIRES=\".*\<${pkg}\( \|\"\)" */*/*.info
    git grep -l -G -e "^REQUIRES=\".*\<${pkg}\( \|\"\)" -- '*/*/*.info' |
        cut -d/ -f1-2 | sort
}

is_installed() {
    local -a candidates
    candidates=( $PKGDB/${1}-*-*-*_{SBo,slonly}(N) )
    if (( $#candidates > 0 ))
    then
        return 0
    else
        return 1
    fi
}

if (( $mode_revdeps ))
then
    queue=($@)
    while (( $#queue > 0 ))
    do
        arg=${queue[1]}
        shift queue

        if is_seen $arg
        then
            continue
        fi
        seen+=$arg

        deps=($( revdeps $arg ))
        if (( $#deps == 0 ))
        then
            continue
        fi

        print -- "dependent on $arg"
        for r in $deps
        do
            rpkg=${r##*/}
            if is_installed $rpkg
            then
                printf " *  %s\n" $r
                if (( $mode_recrevdeps )) && ! is_seen $rpkg
                then
                    queue+=$rpkg
                fi
            else
                printf "    %s\n" $r
            fi
        done
    done
    exit 0
fi

#-----------------------------------------------------------------------------#

# Check updates

checkupdates() {
    local -a candidates
    if (( $# == 0 ))
    then
        candidates=( $PKGDB/*_{SBo,slonly}(N) )
    else
        local arg
        for arg
        do
            candidates+=( $PKGDB/*${arg}*{SBo,slonly}(N) )
        done
        if (( $#candidates == 0 ))
        then
            print "No installed packages matching: $@"
            return
        fi
    fi
    local file
    for file in $candidates
    do
        split_pkg_name $file
        local pkg=$match[1]
        local installed_version=$match[2]
        local pkg_dir=$(find_pkg_dir $pkg softly)
        if [[ ! -d $pkg_dir ]]
        then
            printf -- "%39s ->  %s\n" "(not found)" ${file:t}
            continue
        fi
        local info=$pkg_dir/$pkg.info
        . $info # XXX makes a mess

        if [[ $VERSION != $installed_version ]]
        then
            printf -- "%-39s ->  %s\n" "$pkg $VERSION" ${file:t}
        fi
    done
}

if (( $mode_checkupdates ))
then
    checkupdates "$@"
    exit 0
fi

#-----------------------------------------------------------------------------#

# Clean up mode

if (( $mode_cleanup ))
then
    for pkg
    do
        if ! remove_stagedir $pkg
        then
            exit 1
        fi
    done
    exit 0
fi

#-----------------------------------------------------------------------------#

top_pkgs=()
for pkg
do
    case $pkg in
        (~*) excluded+=${pkg#\~} ;;
        (*) top_pkgs+=$pkg ;;
    esac
done
debug "exclusions: $excluded"

for top_pkg in $top_pkgs
do
    add_deps $top_pkg
done
unset top_pkg

if (( $#queue == 0 ))
then
    die "No packages queued."
fi

if (( $mode_dryrun ))
then
    print "Would build packages in this order:"
    print "  $queue"
    exit 0
fi

mkdir -p $CACHEDIR
mkdir -p $STAGEDIR
mkdir -p $LOGDIR

for pkg in $queue
do
    if (( ${+top_pkgs[(re)$pkg]} ))
    then
        if same_version_installed $pkg
        then
            print -- "$pkg (same version) already installed."
            print -n -- "Process anyway [y,n]? "
            read yn
            case $yn in
                ([yY]) ;;
                (*)
                    echo "Skipping $pkg."
                    continue
                    ;;
            esac
        fi
    elif some_version_installed $pkg
    then
        print -- "$pkg already installed, skipping."
        continue
    fi

    cd $CACHEDIR
    local logfile=$LOGDIR/$pkg.log

    local -A srcfns
    download_src $pkg

    local pkg_filename=

    if (( $mode_build ))
    then
        print "Building $pkg"
        rm -f $logfile $logfile.xz
        if ! build $pkg $srcfns >& /dev/stdout >& $logfile
        then
            die "build failed"
        fi

        pkg_filename=$(extract_built_pkg_filename $logfile)
        xz $logfile

        remove_stagedir $pkg
        print
    fi

    if (( $mode_install ))  # currently implies mode_build
    then
        print "Installing $pkg (enter sudo password if required)"
        if ! install $pkg_filename
        then
            die "install failed"
        fi
    fi
done

#-----------------------------------------------------------------------------#
# vim: set sts=4 sw=4 et:
